/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    Accordion: typeof import('./src/components/Accordion.vue')['default']
    CloudImage: typeof import('./src/components/CloudImage.vue')['default']
    Community: typeof import('./src/components/Community.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home_page: typeof import('./src/components/Home_page.vue')['default']
    HomeContent: typeof import('./src/components/HomeContent.vue')['default']
    LandingPage: typeof import('./src/components/LandingPage.vue')['default']
    ListComment: typeof import('./src/components/ListComment.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Music: typeof import('./src/components/Music.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NPagination: typeof import('naive-ui')['NPagination']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PushFile: typeof import('./src/components/PushFile.vue')['default']
    Regarding: typeof import('./src/components/Regarding.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./src/components/SearchFilter.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SlideOut: typeof import('./src/components/SlideOut.vue')['default']
    SlideShow: typeof import('./src/components/SlideShow.vue')['default']
    TestDownload: typeof import('./src/components/TestDownload.vue')['default']
    TimeLine: typeof import('./src/components/TimeLine.vue')['default']
    UpLoad: typeof import('./src/components/UpLoad.vue')['default']
  }
}
